### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Cosetto** [regomne/lneditor#2]
before: ![image](https://user-images.githubusercontent.com/81801486/126025688-421fc45b-cea6-411c-a046-daca3b2fd2c6.png)
after I reopen it in NewSC: 
![image](https://user-images.githubusercontent.com/81801486/126025713-72760cfc-3aa3-457a-b048-67d4ab39c8dc.png)
How to fix this?

**Comment by regomne** [comment]
I'm sorry but this project is deprecated and not in maintenence.
